blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/JoviDeCroock/drydock/security/advisories/new
    about: Please disclose vulnerabilities privately.
