export const DETERMINISTIC_RULE_IDS = {
  installScriptPreinstall: "install-script.preinstall",
  installScript: "install-script.lifecycle",
  codeProcessExecution: "code.process-execution",
  codeRemoteShell: "code.remote-shell",
  codeNetworkAccess: "code.network-access",
  codeDynamicEvaluation: "code.dynamic-evaluation",
  codeCredentialAccess: "code.credential-access",
  fileSecretContent: "file.secret-content",
  fileLargeBinary: "file.large-binary",
  fileNativeArtifact: "file.native-artifact",
  fileOutsideFilesList: "file.outside-files-list",
  installScriptImplicitNodeGyp: "install-script.implicit-node-gyp",
  installScriptGypCommandSubstitution: "install-script.gyp-command-substitution",
  packageJsonParseFailed: "package-json.parse-failed",
  packageJsonEntrypointMissing: "package-json.entrypoint-missing",
  diffCredentialFileAdded: "diff.credential-file-added",
  diffLargeNewFile: "diff.large-new-file",
  diffBinAdded: "diff.bin-added",
  dependencyUnusualSpec: "dependency.unusual-spec",
  dependencyOptionalAdded: "dependency.optional-added",
  dependencyAdded: "dependency.added",
  dependencyMajorBump: "dependency.major-bump",
  // `dependency-artifact.*` describes the *fetched bytes* of a dependency this
  // release newly introduces, not the manifest line that declares it (that is
  // the `dependency.*` family above).
  dependencyArtifactInstallRisk: "dependency-artifact.install-risk",
  dependencyArtifactInstallExecution: "dependency-artifact.install-execution",
  dependencyArtifactCapability: "dependency-artifact.capability",
  dependencyArtifactIntegrityMismatch: "dependency-artifact.integrity-mismatch",
  dependencyArtifactUninspectable: "dependency-artifact.uninspectable",
  stageMetadataMismatch: "stage.metadata-mismatch",
  stageTarballDigestMismatch: "stage.tarball-digest-mismatch",
  atpmProvenanceMissing: "atpm.provenance-missing",
  atpmProvenanceInvalid: "atpm.provenance-invalid",
  atpmProvenanceSubjectMismatch: "atpm.provenance-subject-mismatch",
  atpmProvenancePublisherMismatch: "atpm.provenance-publisher-mismatch",
  atpmTrustedPublishingLost: "atpm.trusted-publishing-lost",
  tarSuspiciousEntry: "tar.suspicious-entry",
  releaseSourceDrift: "release.source-drift",
} as const;

export type DeterministicRuleKey = keyof typeof DETERMINISTIC_RULE_IDS;
