export const DETERMINISTIC_RULE_IDS = {
  installScriptPreinstall: "install-script.preinstall",
  installScript: "install-script.lifecycle",
  codeProcessExecution: "code.process-execution",
  codeRemoteShell: "code.remote-shell",
  codeNetworkAccess: "code.network-access",
  codeDynamicEvaluation: "code.dynamic-evaluation",
  codeCredentialAccess: "code.credential-access",
  fileSecretContent: "file.secret-content",
  fileLargeBinary: "file.large-binary",
  fileNativeArtifact: "file.native-artifact",
  fileOutsideFilesList: "file.outside-files-list",
  installScriptImplicitNodeGyp: "install-script.implicit-node-gyp",
  installScriptGypCommandSubstitution: "install-script.gyp-command-substitution",
  packageJsonParseFailed: "package-json.parse-failed",
  packageJsonEntrypointMissing: "package-json.entrypoint-missing",
  diffCredentialFileAdded: "diff.credential-file-added",
  diffLargeNewFile: "diff.large-new-file",
  diffBinAdded: "diff.bin-added",
  dependencyUnusualSpec: "dependency.unusual-spec",
  dependencyOptionalAdded: "dependency.optional-added",
  dependencyAdded: "dependency.added",
  dependencyMajorBump: "dependency.major-bump",
  stageMetadataMismatch: "stage.metadata-mismatch",
  stageTarballDigestMismatch: "stage.tarball-digest-mismatch",
  tarSuspiciousEntry: "tar.suspicious-entry",
  releaseSourceDrift: "release.source-drift",
} as const;

export type DeterministicRuleKey = keyof typeof DETERMINISTIC_RULE_IDS;
